[package]
name = "ntdsextract2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
    
[dependencies]
log = {version = "0.4", features = [ "release_max_level_info" ]}
simplelog = "0.12"
anyhow = "1.0"
clap = "3"
clap-verbosity-flag = "1.0.0"

bodyfile = "0.1.4"
libesedb = {version = "0.1.3", path = "../rust-libesedb"}
